"""
ApsimX integration for MLPlayground.

Runs ApsimX crop simulations using daily weather and soil data from the
MLPlayground database, then returns simulated annual yields as a DataFrame
for comparison against observed USDA NASS yields.

Requires the ApsimX CLI binary to be built (set APSIMX_BIN env var or run
scripts/install_apsimx.sh).
"""
import json
import logging
import os
import sqlite3
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

import pandas as pd

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

APSIMX_BIN = os.environ.get("APSIMX_BIN", "/tmp/apsim_sc/apsim")
APSIMX_TEMPLATE = Path(__file__).parent / "apsimx_templates" / "Maize.apsimx"

# Mapping from crop names (as stored in the DB) to ApsimX example filenames
# and sowing window parameters.
CROP_CONFIG: dict[str, dict] = {
    "CORN": {
        "template": "Maize.apsimx",
        "crop_model": "Maize",
        "cultivar": "Dekalb_XL82",
        "sow_start": "1-may",
        "sow_end": "15-jun",
        "sowing_depth": 40.0,
        "row_spacing": 760.0,
        "population": 7.5,
    },
    "SOYBEANS": {
        "template": "Soybean.apsimx",
        "crop_model": "Soybean",
        "cultivar": "Davis",
        "sow_start": "1-may",
        "sow_end": "30-jun",
        "sowing_depth": 35.0,
        "row_spacing": 760.0,
        "population": 35.0,
    },
}

# ---------------------------------------------------------------------------
# .met file generation
# ---------------------------------------------------------------------------

def _compute_tav_amp(df: pd.DataFrame, maxt_col: str = "tmax", mint_col: str = "tmin") -> tuple[float, float]:
    """Compute annual average temperature (tav) and amplitude (amp) for .met header."""
    df = df.copy()
    df["tmean"] = (df[maxt_col] + df[mint_col]) / 2.0
    df["month"] = pd.to_datetime(df["date"]).dt.month
    monthly_mean = df.groupby("month")["tmean"].mean()
    tav = float(monthly_mean.mean())
    amp = float((monthly_mean.max() - monthly_mean.min()) / 2.0)
    return round(tav, 2), round(amp, 2)


def generate_met_file_from_df(df_county: pd.DataFrame, output_path: str) -> None:
    """
    Write an ApsimX .met file from a DataFrame that already has columns:
      year, day_of_year (or day), tmax, tmin, prcp, srad, vp, dayl
    (as returned by querying the DailyWeather table).
    """
    # Normalise column names — DB uses snake_case, .met file uses short names
    rename = {"DayOfYear": "day", "day_of_year": "day",
               "Year": "year", "tmax": "maxt", "tmin": "mint",
               "prcp": "rain", "County": "county"}
    df = df_county.rename(columns={k: v for k, v in rename.items() if k in df_county.columns}).copy()

    df["radn"] = (df["srad"] * df["dayl"] / 1e6).round(2)   # W/m² × s / 1e6 = MJ/m²/day
    df["vp_hpa"] = (df["vp"] / 100.0).round(2)               # Pa → hPa
    df["rain"] = df["rain"].round(2)
    df = df.sort_values(["year", "day"])

    tav, amp = _compute_tav_amp(df, maxt_col="maxt", mint_col="mint")

    lines = [
        "[weather.met.weather]",
        "latitude = 35.5  (DECIMAL DEGREES)",
        "longitude = -79.0  (DECIMAL DEGREES)",
        f"tav = {tav} (oC)",
        f"amp = {amp} (oC)",
        "!Generated by MLPlayground from database (Daymet/NLDAS source)",
        "",
        "year  day   radn   maxt    mint    rain    vp",
        " ()   ()  (MJ/m^2) (oC)   (oC)    (mm)   (hPa)",
    ]
    for _, row in df[["year", "day", "radn", "maxt", "mint", "rain", "vp_hpa"]].iterrows():
        lines.append(
            f"{int(row['year']):4d} {int(row['day']):4d} {row['radn']:7.2f} "
            f"{row['maxt']:7.2f} {row['mint']:7.2f} {row['rain']:7.2f} {row['vp_hpa']:7.2f}"
        )
    Path(output_path).write_text("\n".join(lines))
    logger.info("Wrote .met file to %s (%d rows)", output_path, len(df))



    df_county = df_county.rename(columns={"day_of_year": "day"})
    generate_met_file_from_df(df_county, output_path)


def generate_met_file_from_db(
    county: str,
    state: str,
    start_year: int,
    end_year: int,
    session,
    output_path: str,
) -> None:
    """
    Query the DailyWeather table and write a .met file.
    The DB is populated by running POST /api/v1/ingest/trigger-daily-weather.
    """
    from app.models import DailyWeather as DWModel
    from sqlmodel import select

    rows = session.exec(
        select(DWModel).where(
            DWModel.county == county,
            DWModel.state == state,
            DWModel.year >= start_year,
            DWModel.year <= end_year,
        )
    ).all()

    if not rows:
        raise ValueError(
            f"No daily weather data in DB for {county}, {state} ({start_year}–{end_year}). "
            "Run POST /api/v1/ingest/trigger-daily-weather first."
        )

    df = pd.DataFrame([{
        "year": r.year, "day": r.day_of_year, "date": r.date,
        "maxt": r.tmax, "mint": r.tmin, "rain": r.prcp,
        "srad": r.srad, "vp": r.vp, "dayl": r.dayl,
    } for r in rows])

    generate_met_file_from_df(df, output_path)


# ---------------------------------------------------------------------------
# .apsimx template patching
# ---------------------------------------------------------------------------

def _find_and_patch(node: dict | list, patches: dict) -> None:
    """
    Recursively walk the .apsimx JSON tree, applying patches.
    patches keys are '$type' fragment → dict of field→value to set.
    """
    if isinstance(node, dict):
        t = node.get("$type", "")
        for type_frag, fields in patches.items():
            if type_frag in t:
                node.update(fields)
        for v in node.values():
            _find_and_patch(v, patches)
    elif isinstance(node, list):
        for item in node:
            _find_and_patch(item, patches)


def _patch_manager_params(node: dict | list, manager_name: str, param_updates: dict) -> None:
    """Update specific Parameters keys in a named Manager node."""
    if isinstance(node, dict):
        if "Manager" in node.get("$type", "") and node.get("Name") == manager_name:
            for param in node.get("Parameters", []):
                if param["Key"] in param_updates:
                    param["Value"] = str(param_updates[param["Key"]])
        for v in node.values():
            _patch_manager_params(v, manager_name, param_updates)
    elif isinstance(node, list):
        for item in node:
            _patch_manager_params(item, manager_name, param_updates)


def build_apsimx_file(
    template_path: str,
    met_file: str,
    start_year: int,
    end_year: int,
    crop_cfg: dict,
    output_path: str,
    soil_props: Optional[dict] = None,
) -> None:
    """
    Patch an .apsimx template with local weather, dates, crop parameters,
    and optionally soil properties from the database.

    Parameters
    ----------
    soil_props : dict, optional
        Keys: ph, organic_matter, sand_pct, clay_pct (from the Soil DB table).
        These are applied uniformly across all soil layers in the template.
    """
    with open(template_path) as f:
        sim = json.load(f)

    # Patch Clock
    _find_and_patch(sim, {
        "Models.Clock,": {
            "Start": f"{start_year}-01-01T00:00:00",
            "End": f"{end_year}-12-31T00:00:00",
        }
    })

    # Patch Weather file path
    _find_and_patch(sim, {
        "Models.Climate.Weather,": {
            "FileName": str(met_file),
        }
    })

    # Patch Sowing Manager parameters
    _patch_manager_params(sim, "Sow using a variable rule", {
        "Crop": crop_cfg["crop_model"],
        "CultivarName": crop_cfg["cultivar"],
        "StartDate": crop_cfg["sow_start"],
        "EndDate": crop_cfg["sow_end"],
        "SowingDepth": crop_cfg["sowing_depth"],
        "RowSpacing": crop_cfg["row_spacing"],
        "Population": crop_cfg["population"],
    })

    # Patch soil properties from the Soil DB table.
    # We apply uniform bulk properties across all layers as a first approximation.
    if soil_props:
        _patch_soil_properties(sim, soil_props)

    with open(output_path, "w") as f:
        json.dump(sim, f, indent=2)

    logger.info("Built .apsimx file at %s (years %d-%d, soil=%s)", output_path, start_year, end_year,
                "DB" if soil_props else "template default")


def _patch_soil_properties(sim: dict, soil_props: dict) -> None:
    """
    Walk the .apsimx JSON and apply bulk soil properties uniformly to all layers.
    Currently patches: ParticleSizeSand, ParticleSizeClay, and SoilOrganicMatter.
    pH is not a direct ApsimX Physical node field but is noted in the model description.
    """
    def walk(node):
        if isinstance(node, dict):
            t = node.get("$type", "")
            # Patch Physical layer arrays (sand/clay expressed as % → fraction)
            if "Models.Soils.Physical," in t:
                n_layers = len(node.get("BD", [1]))  # use BD length to get layer count
                if "sand_pct" in soil_props and soil_props["sand_pct"] is not None:
                    node["ParticleSizeSand"] = [round(soil_props["sand_pct"], 1)] * n_layers
                if "clay_pct" in soil_props and soil_props["clay_pct"] is not None:
                    node["ParticleSizeClay"] = [round(soil_props["clay_pct"], 1)] * n_layers
            # Patch Organic (formerly SoilOrganicMatter) node
            if "Models.Soils.Organic," in t:
                n_layers = len(node.get("Carbon", [1]))
                if "organic_matter" in soil_props and soil_props["organic_matter"] is not None:
                    # ApsimX Organic uses Carbon (%) not OM (%). OM ≈ C × 1.72
                    carbon_pct = round(soil_props["organic_matter"] / 1.72, 3)
                    node["Carbon"] = [carbon_pct] * n_layers
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for item in node:
                walk(item)
    walk(sim)


# ---------------------------------------------------------------------------
# Run ApsimX and parse output
# ---------------------------------------------------------------------------

def run_apsimx(apsimx_file: str, work_dir: str) -> Optional[pd.DataFrame]:
    """
    Run the ApsimX CLI on apsimx_file (in work_dir) and return a DataFrame
    with columns [year, simulated_yield_kg_ha].
    """
    if not Path(APSIMX_BIN).exists():
        raise FileNotFoundError(
            f"ApsimX binary not found at '{APSIMX_BIN}'. "
            "Set the APSIMX_BIN environment variable to the path of the apsim CLI binary. "
            "Build it with: dotnet publish ApsimX/APSIM.Cli/APSIM.Cli.csproj "
            "-f net8.0 --self-contained true -r osx-arm64 -o /tmp/apsim_sc"
        )

    db_file = str(Path(apsimx_file).with_suffix(".db"))
    if Path(db_file).exists():
        Path(db_file).unlink()

    result = subprocess.run(
        [APSIMX_BIN, "run", apsimx_file],
        capture_output=True,
        text=True,
        cwd=work_dir,
        timeout=300,
    )

    if result.returncode != 0:
        logger.error("ApsimX failed:\n%s\n%s", result.stdout[-2000:], result.stderr[-2000:])
        raise RuntimeError(f"ApsimX simulation failed: {result.stdout[-500:]}")

    if not Path(db_file).exists():
        raise FileNotFoundError(f"ApsimX did not produce a .db file at {db_file}")

    conn = sqlite3.connect(db_file)
    try:
        df = pd.read_sql("SELECT * FROM Report", conn)
    finally:
        conn.close()

    if df.empty:
        return None

    # Parse harvest year from the Clock.Today date and extract yield
    df["harvest_date"] = pd.to_datetime(df["Clock.Today"])
    df["year"] = df["harvest_date"].dt.year
    # Yield column is in kg/ha in ApsimX output
    df = df.rename(columns={"Yield": "simulated_yield_kg_ha"})
    return df[["year", "simulated_yield_kg_ha"]].copy()


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def simulate_yields(
    county: str,
    crop: str,
    start_year: int,
    end_year: int,
    session=None,
    state: str = "North Carolina",
    apsimx_templates_dir: Optional[str] = None,
) -> Optional[pd.DataFrame]:
    """
    Run ApsimX for a single county and return simulated yields by year.
    Daily weather and soil data are read from the DB (DailyWeather + Soil tables).
    Trigger ``POST /api/v1/ingest/trigger-daily-weather`` if no rows are present.

    Returns a DataFrame with columns: year, simulated_yield_kg_ha
    """
    crop_upper = crop.upper()
    if crop_upper not in CROP_CONFIG:
        logger.warning("ApsimX has no template for crop '%s'. Supported: %s", crop, list(CROP_CONFIG))
        return None

    cfg = CROP_CONFIG[crop_upper]

    if apsimx_templates_dir is None:
        apsimx_templates_dir = str(Path(__file__).parent / "apsimx_templates")

    template_path = str(Path(apsimx_templates_dir) / cfg["template"])
    if not Path(template_path).exists():
        raise FileNotFoundError(
            f"ApsimX template not found: {template_path}. "
            "Copy the template from the ApsimX Examples directory into "
            "backend/app/ingest/apsimx_templates/."
        )

    if session is None:
        raise ValueError(
            f"A database session is required to run ApsimX for {county}. "
            "Ensure daily weather has been ingested via POST /api/v1/ingest/trigger-daily-weather."
        )

    with tempfile.TemporaryDirectory(prefix="apsimx_") as work_dir:
        met_file = str(Path(work_dir) / f"{county}.met")

        # --- weather (DB only) ---
        generate_met_file_from_db(county, state, start_year, end_year, session, met_file)
        logger.info("Using DB daily weather for %s, %s", county, state)

        # --- soil ---
        soil_props = None
        if session is not None:
            from app.models import Soil
            from sqlmodel import select
            soil_row = session.exec(
                select(Soil).where(Soil.county == county, Soil.state == state)
            ).first()
            if soil_row:
                soil_props = {
                    "ph": soil_row.ph,
                    "organic_matter": soil_row.organic_matter,
                    "sand_pct": soil_row.sand_pct,
                    "clay_pct": soil_row.clay_pct,
                }
                logger.info("Using DB soil properties for %s: %s", county, soil_props)

        apsimx_file = str(Path(work_dir) / "simulation.apsimx")
        build_apsimx_file(
            template_path=template_path,
            met_file=met_file,
            start_year=start_year,
            end_year=end_year,
            crop_cfg=cfg,
            output_path=apsimx_file,
            soil_props=soil_props,
        )

        return run_apsimx(apsimx_file, work_dir)
