"""Remove county_ansi and district from weather and soil

Revision ID: 055089708af5
Revises: 58b69e9c9b56
Create Date: 2025-10-05 22:23:40.702914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055089708af5'
down_revision: Union[str, Sequence[str], None] = '58b69e9c9b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soil', 'county_ansi')
    op.drop_column('soil', 'district')
    op.drop_column('weather', 'county_ansi')
    op.drop_column('weather', 'district')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('county_ansi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('soil', sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('soil', sa.Column('county_ansi', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
