"""Initial tables

Revision ID: 58b69e9c9b56
Revises: 
Create Date: 2025-10-05 15:22:22.731906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b69e9c9b56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county', sa.String(), nullable=False),
    sa.Column('county_ansi', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('organic_matter', sa.Float(), nullable=True),
    sa.Column('sand_pct', sa.Float(), nullable=True),
    sa.Column('silt_pct', sa.Float(), nullable=True),
    sa.Column('clay_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county', sa.String(), nullable=False),
    sa.Column('county_ansi', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('avg_temp', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('min_temp', sa.Float(), nullable=True),
    sa.Column('max_temp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=False),
    sa.Column('county_ansi', sa.String(), nullable=True),
    sa.Column('crop', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yields')
    op.drop_table('weather')
    op.drop_table('soil')
    # ### end Alembic commands ###
