"""remove month and day from weather

Revision ID: 822630149253
Revises: 9905ef6ffa90
Create Date: 2025-10-05 22:46:11.660716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822630149253'
down_revision: Union[str, Sequence[str], None] = '9905ef6ffa90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather', 'month')
    op.drop_column('weather', 'day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
