"""add gdd and vp and srad to weather

Revision ID: 9905ef6ffa90
Revises: 2d5bdfe171b1
Create Date: 2025-10-05 22:40:59.088130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9905ef6ffa90'
down_revision: Union[str, Sequence[str], None] = '2d5bdfe171b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('vp', sa.Float(), nullable=True))
    op.add_column('weather', sa.Column('srad', sa.Float(), nullable=True))
    op.add_column('weather', sa.Column('gdd', sa.Float(), nullable=True))
    op.drop_column('weather', 'min_temp')
    op.drop_column('weather', 'max_temp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('max_temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('min_temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('weather', 'gdd')
    op.drop_column('weather', 'srad')
    op.drop_column('weather', 'vp')
    # ### end Alembic commands ###
