"""Add weather_psa table

Revision ID: ca8acb2dc3e2
Revises: 003_add_model_runs
Create Date: 2026-02-26 21:26:59.158167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ca8acb2dc3e2'
down_revision: Union[str, None] = '003_add_model_runs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_psa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('county', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('longwave_radiation', sa.Float(), nullable=True),
    sa.Column('shortwave_radiation', sa.Float(), nullable=True),
    sa.Column('potential_energy', sa.Float(), nullable=True),
    sa.Column('potential_evaporation', sa.Float(), nullable=True),
    sa.Column('convective_precipitation', sa.Float(), nullable=True),
    sa.Column('min_air_temperature', sa.Float(), nullable=True),
    sa.Column('max_air_temperature', sa.Float(), nullable=True),
    sa.Column('avg_air_temperature', sa.Float(), nullable=True),
    sa.Column('min_humidity', sa.Float(), nullable=True),
    sa.Column('max_humidity', sa.Float(), nullable=True),
    sa.Column('avg_humidity', sa.Float(), nullable=True),
    sa.Column('min_relative_humidity', sa.Float(), nullable=True),
    sa.Column('max_relative_humidity', sa.Float(), nullable=True),
    sa.Column('avg_relative_humidity', sa.Float(), nullable=True),
    sa.Column('min_pressure', sa.Float(), nullable=True),
    sa.Column('max_pressure', sa.Float(), nullable=True),
    sa.Column('avg_pressure', sa.Float(), nullable=True),
    sa.Column('min_zonal_wind_speed', sa.Float(), nullable=True),
    sa.Column('max_zonal_wind_speed', sa.Float(), nullable=True),
    sa.Column('avg_zonal_wind_speed', sa.Float(), nullable=True),
    sa.Column('min_meridional_wind_speed', sa.Float(), nullable=True),
    sa.Column('max_meridional_wind_speed', sa.Float(), nullable=True),
    sa.Column('avg_meridional_wind_speed', sa.Float(), nullable=True),
    sa.Column('min_wind_speed', sa.Float(), nullable=True),
    sa.Column('max_wind_speed', sa.Float(), nullable=True),
    sa.Column('avg_wind_speed', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_daily_weather_county_year'), table_name='daily_weather')
    op.alter_column('model_runs', 'datasources',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('model_runs', 'join_keys',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('model_runs', 'feature_columns',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('model_runs', 'filters',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('ix_model_runs_run_id'), table_name='model_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_model_runs_run_id'), 'model_runs', ['run_id'], unique=True)
    op.alter_column('model_runs', 'filters',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('model_runs', 'feature_columns',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('model_runs', 'join_keys',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('model_runs', 'datasources',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_daily_weather_county_year'), 'daily_weather', ['county', 'state', 'year'], unique=False)
    op.drop_table('weather_psa')
    # ### end Alembic commands ###
